services:
  vault:
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200" # Expose the Vault API
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    networks:
      - backtier

  user:
    build:
      context: ./Backend/userService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/userService:/app
    environment:
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "user_db"
      DB_PORT: "5432"
    depends_on:
      - vault
      - user_db
    networks:
      - backtier
      - user_network

  user_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - backtier
      - user_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - vault
      - user
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - backtier

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    volumes:
      - frontend_dist:/app/dist # Mount volume to persist the dist/ folder
    environment:
      - NODE_ENV=production
    networks:
      - backtier
      - frontier

volumes:
  user_db_data:
  frontend_dist:

networks:
  user_network:
    driver: bridge
  backtier:
    driver: bridge
  frontier:
    driver: bridge
