# Generated by Django 5.1.3 on 2024-11-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/'),
        ),
    ]
