# Generated by Django 5.1.3 on 2024-11-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
