# Generated by Django 5.1.5 on 2025-02-06 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0002_profile_blocked_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['participant1'], name='userService_partici_160674_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['participant2'], name='userService_partici_cedf69_idx'),
        ),
    ]
