# Generated by Django 5.1.6 on 2025-02-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0003_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
