# Generated by Django 5.1.3 on 2024-11-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0005_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
