# Generated by Django 5.1.3 on 2024-11-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0006_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='match_history',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wins',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/default.png', upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='MatchHistory',
        ),
    ]
