# Generated by Django 5.1.3 on 2024-11-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0007_remove_matchhistory_opponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
