# Generated by Django 5.1.3 on 2024-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0009_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='friend_set', through='userService.Friendship', to='userService.profile'),
        ),
    ]
