# Generated by Django 5.1.5 on 2025-01-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0013_chatmodel_chatnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
