# Generated by Django 5.1.5 on 2025-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userService', '0014_alter_chatmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='sender',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='thread_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
