# Generated by Django 5.1.6 on 2025-02-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chat',
            name='chatService_partici_271259_idx',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='chatService_partici_42a1c6_idx',
        ),
    ]
